### PR TITLE
Update firepwd.py

### PR DESCRIPTION
**Pull request by XFJH**
fix bug
I meeted a str  param not windowspath Exception on  376 line sqlite3.connect() method。

### CODE REVIEW

**Comment by cornfeedhobo** [comment]
There is a similar issue with the handling of `signons.sqlite`

**Comment by Rammy61** [comment]
Hi, I am strugling with a error given in line 64 of the firepwd.py script, print ('  '*rl, asn1Types[ type ],end=' ') SyntaxError: invalid syntax. I use this script on X-Ubuntu 22.04 LTS with firefox version 110.0 64bits with key4.db. In the past the script functions without problems on X-Ubuntu 18.04 LTS and firefox with key3.db. Can you tell me what goes wrong here and how I could solve the problem.

Regards.

Ramcsir

**Comment by lclevy** [comment]
what is your exact command line ?

> Hi, I am strugling with a error given in line 64 of the firepwd.py script, print (' '*rl, asn1Types[ type ],end=' ') SyntaxError: invalid syntax. I use this script on X-Ubuntu 22.04 LTS with firefox version 110.0 64bits with key4.db. In the past the script functions without problems on X-Ubuntu 18.04 LTS and firefox with key3.db. Can you tell me what goes wrong here and how I could solve the problem.
> 
> Regards.
> 
> Ramcsir

**Comment by Rammy61** [comment]
I use the code below,
		pwd_old=$PWD
		cd $home_firepwd
		python2.7 firepwd.py -d ./ | sed 's:\\x0[0-9]::g' >"${f_tmp_0}"
	#	cd ..
		cd $pwd_old

It goes wrong when calling the python2.7 firepwd.py script. When the error is reported the f_tmp_0 file is ofcourse empty.

**Comment by Rammy61** [comment]
I changed the python2.7 in python3 and get an error back saying, 
Traceback (most recent call last): File "/home/pi/firepwd/firepwd.py", line 25, in <module> from pyasn1.codec.der import decoder ModuleNotFoundError: No module named 'pyasn1'

**Comment by lclevy** [comment]
Read the doc

**Comment by lclevy** [comment]
Readme.md

**Comment by lclevy** [comment]
Pip install is installing for python 2.7. you must use pip3

**Comment by lclevy** [comment]
Readme examples are on Windows

**Comment by Rammy61** [comment]
After installing, pip3 install PyCryptodome, your firepwd software works again. Thanks that you spent time on my problem.

**Comment by lclevy** [comment]
Not enough information for bug reproduction

**Pull request closed without merging**
